name: Build & Test
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
env:
    GOPATH: ${{ github.workspace }}
    GOBIN: ${{ github.workspace }}/bin
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ${{ env.GOPATH }}/src/web-api-go
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: ${{ env.GOPATH }}/src/web-api-go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: subdir/go.sum
      - name: Test
        run: go test -v ./...
        
      - name: Install dependencies
        run: |
          go version
          go get -u github.com/go-chi/chi/v5 
          go get -u github.com/golang-jwt/jwt
          go get -u github.com/jmoiron/sqlx
          go get -u github.com/joho/godotenv
          go get -u github.com/lib/pq
          go get -u golang.org/x/crypto

      - name: Build
        run: go build -v ./...
